---
version: "3.8"

services:
  app:
    environment:
      - SOURCES_YML_URL=$SOURCES_YML_URL
    image: moonlion/agora-server:testing
    volumes:
      - data:/home/root/agora
    ports:
      - 5017:5017
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=5017"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${DOMAIN}`${EXTRA_DOMAINS})"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=web-secure"
        - "traefik.http.routers.${STACK_NAME}.tls.certresolver=${LETS_ENCRYPT_ENV}"
        ## Redirect from EXTRA_DOMAINS to DOMAIN
        #- "traefik.http.routers.${STACK_NAME}.middlewares=${STACK_NAME}-redirect"
        #- "traefik.http.middlewares.${STACK_NAME}-redirect.headers.SSLForceHost=true"
        #- "traefik.http.middlewares.${STACK_NAME}-redirect.headers.SSLHost=${DOMAIN}"
        - "coop-cloud.${STACK_NAME}.version="
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5017"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 1m
  bridge:
    environment:
      - SOURCES_YML_URL=$SOURCES_YML_URL
    image: moonlion/agora-bridge:testing
    volumes:
      - data:/agora-bridge
    deploy:
      restart_policy:
        condition: none
    

networks:
  proxy:
    external: true
volumes:
  data: